export const imgs = {

  Profile: require('./profile.png'),
  Profile2: require('./profile2.png'),
  Profile3: require('./profile3.png'),
  Profile4: require('./profile4.png'),
  EventPost: require('./eventpost.png'),
  EventPost2: require('./eventpost2.png'),


  UploadImg: require('./signupprofile.png'),

  Logo: require('./logo/logo.png'),
  LogoBlue: require('./logo/blue.png'),
  Espn: require('./logo/espn.png'),
  Fantasy: require('./logo/fantasy.png'),
  Sleeper: require('./logo/sleeper.png'),
  Yahoo: require('./logo/yahoo.png'),

  Monkey: require('./logo/monkey.png'),
  Spulse: require('./logo/spulse.png'),
  VS: require('./logo/vs.png'),
  Avengers: require('./logo/avengers.png'),

  BG: require('./bg.png'),
  bg1: require('./bg-1.png'),
  bg2: require('./bg-2.png'),
  bg3: require('./bg-3.png'),
  avatar: require('./avatar.png'),
  flower: require('./flower.jpg'),
  PostBg1: require('./background1.jpeg'),
  PostBg2: require('./background2.jpeg'),
  background3: require('./background3.jpg'),
  Property: require('./property.png'),



}

export const icons = {
  NoPhoto: require('./icons/nophoto.png'),
  Cross: require('./icons/cross.png'),
  CrossRed: require('./icons/crossred.png'),
  Smile: require('./icons/smile.png'),
  UploadRed: require('./icons/uploadred.png'),
  Setting: require('./icons/settings.png'),
  Delete: require('./icons/delete.png'),
  Edit1: require('./icons/edit-1.png'),
  Home: require('./icons/home.png'),
  Users: require('./icons/users.png'),
  Plus: require('./icons/plus.png'),
  RightArrow: require('./icons/caret-down.png'),
  Edit: require('./icons/edit.png'),
  Back: require('./icons/back.png'),
  Marker: require('./icons/marker.png'),
  Search: require('./icons/search.png'),
  Notification: require('./icons/notification.png'),
  Message: require('./icons/messages.png'),
  Upload: require('./icons/upload.png'),
  Lock: require('./icons/lock.png'),
  Mail: require('./icons/mail.png'),
  Phone: require('./icons/phone.png'),
  Profile: require('./icons/profile.png'),
  Menu: require('./icons/menu.png'),
  Google: require('./icons/google.png'),
  Apple: require('./icons/apple.png'),
  Facebook: require('./icons/facebook.png'),
  BackArrow: require('./icons/arrow-back.png'),
  LoginMail: require('./icons/login-mail.png'),
  LoginLock: require('./icons/login-lock.png'),
  User: require('./icons/user.png'),
  Clock: require('./icons/clock-five.png'),
  Email: require('./icons/email.png'),
  Eye: require('./eye.png'),
  CutEye: require('./cuteye.png'),
  Business: require('./icons/business-time.png'),
  Smartphone: require('./icons/smartphone.png'),





  DocumentText: require('./icons/document-text.png'),
  MessageQuestion: require('./icons/message-question.png'),
  MoneyReceive: require('./icons/money-recive.png'),
  ProfileCircle: require('./icons/profile-circle.png'),
  Note: require('./icons/note.png'),

  CAM: require('./icons/camera.png'),
  starempty: require('./icons/starEmpty.png'),
  info: require('./icons/info.png'),
  maps: require('./icons/maps.png'),
  starFilled: require('./icons/starFilled.png'),
  filter: require('./icons/filter.png'),
  msg: require('./icons/msg.png'),
  starfilled: require('./icons/starFilled.png'),
  send: require('./icons/send.png'),
  pin: require('./icons/attachment.png'),
  starEmpty: require('./icons/starEmpty.png'),
  subscription: require('./icons/subscription.png'),
  information: require('./icons/information.png'),
  policies: require('./icons/policies.png'),
  home: require('./icons/homelist.png'),
  add: require('./icons/add.png'),
  chat: require('./icons/chatlist.png'),
  celendar: require('./icons/calendar.png'),
  bt4: require('./icons/bt4.png'),
  hidechat: require('./icons/chat.png'),
  eventlst: require('./icons/eventlist.png'),
  hidehome: require('./icons//hidehome.png'),
  profilelist: require('./icons/profilelist.png')
}
