import { RFPercentage } from 'react-native-responsive-fontsize';
export const themes = {
    font: {
        black: "Montserrat-Black",
        blackItalic: "Montserrat-BlackItalic",
        bold: "Montserrat-Bold",
        boldItalic: "Montserrat-BoldItalic",
        extraBold: "Montserrat-ExtraBold",
        extraBoldItalic: "Montserrat-ExtraBoldItalic",
        extraLight: "Montserrat-ExtraLight",
        extraLightItalic: "Montserrat-ExtraLightItalic",
        italic: "Montserrat-Italic",
        light: "Montserrat-Light",
        lightItalic: "Montserrat-LightItalic",
        medium: "Montserrat-Medium",
        mediumItalic: "Montserrat-MediumItalic",
        regular: "Montserrat-Regular",
        semiBold: "Montserrat-SemiBold",
        semiBoldItalic: "Montserrat-SemiBoldItalic",
        thin: "Montserrat-Thin",
        thinItalic: "Montserrat-ThinItalic",

    },
    fontSize: {
        headingSize: RFPercentage(3),
        tiny: RFPercentage(1.3),
        extraVSmall: RFPercentage(1.8),
        extraSmall: RFPercentage(1.9),
        small: RFPercentage(2),
        medium: RFPercentage(2.2),
        regular: RFPercentage(2.4),
        large: RFPercentage(2.6),
        extraLarge: RFPercentage(4),
    },
    colors: {
        lightBlue:'#0493c8',
        darkBlue:'#1c66b5',
        pink: '#8e26ae',
        darkPink:'#c2139e',
        fontColor: '#000000',
        imgBorder: '#888888',
        lightRed: '#EE313B',
        lightPink: '#F954B6',
        grey: '#A7A7A7',
        offWhite: '#F5F5F5',
        lightGrey: '#707070',
        fontBlack: '#282828',
        black: '#000000',
        flashWhite: '#EFF0F6',
        bg: '#EDF7FF',
        red: '#EE313B',
        white: '#FFFFFF',
        icnBlue: '#208DEE',
        fadeBlack: '#3E4187',
        headingBlue: '#222461',
        gray: '#979797',
        textBlue: '#3E4187',
        bgBlue: '#006DCA',
        statusBar: '#fff',
        borderGray: '#D8E2EB',
        borderGrayLight: 'rgba(237, 247, 255, .3)',
        textPurple: '#AC4BEB',
        bgGreen: '#02C369',
        darkGreen: '#6890B2',
        purple: '#4B0081',
        skyBlue: '#3388EC',
        orange: '#E3453A',
        formBg: '#82ADD8',
        error: '#FF6157',
        errorLight: 'rgba(255, 97, 87, 0.15)',
        success: '#61C877',
        successLight: 'rgba(97, 200, 119, 0.15)',
        // lightBorderColor: 'rgba(0, 0, 128, 0.20)',
        primaryLighten: 'rgba(0, 0, 128, 0.20)',
        primaryLight: '#565677',
        // secondary: '#000',
        lightenSecondary: '#A0ADB8',
        lightSecondary: '#F1F1F1',
        tertiary: '#ffffff',
        backgroundColor: '#ffffff',
        backgroundColorLighten: '#F8FAF9',
        lighten: 'rgba(160, 173, 184, 0.3)',
        darken: '#263238',
        lightText: '#7C7D7C',
        shadow: '#707070',
        overlay: 'rgba(124, 128, 97, 0.7)',
    },

};
